local M = {}
local colors = require("gruber.palette")

M.setup = function()
  return {
    Comment = { fg = colors.green, italic = true },
    Constant = { fg = colors.yellow },
    String = { fg = colors.green },
    Character = { fg = colors.green },
    Number = { fg = colors.yellow },
    Boolean = { fg = colors.yellow },
    Float = { fg = colors.yellow },
    Identifier = { fg = colors.fg },
    Function = { fg = colors.blue },
    Statement = { fg = colors.yellow },
    Conditional = { fg = colors.yellow },
    Repeat = { fg = colors.yellow },
    Label = { fg = colors.yellow },
    Operator = { fg = colors.dark_green },
    Keyword = { fg = colors.yellow },
    Exception = { fg = colors.yellow },
    PreProc = { fg = colors.yellow },
    Include = { fg = colors.yellow },
    Define = { fg = colors.yellow },
    Macro = { fg = colors.yellow },
    PreCondit = { fg = colors.yellow },
    Type = { fg = colors.yellow },
    StorageClass = { fg = colors.yellow },
    Structure = { fg = colors.fg },
    Typedef = { fg = colors.fg },
    Special = { fg = colors.yellow },
    SpecialChar = { fg = colors.yellow },
    Tag = { fg = colors.yellow },
    Delimiter = { fg = colors.fg },
    SpecialComment = { fg = colors.green },
    Debug = { fg = colors.yellow },
    Underlined = { underline = true },
    Ignore = { fg = colors.green },
    Error = { fg = colors.red , bold = true },
    Todo = { fg = colors.red, bold = true },
    ["@string"] = { fg = colors.green },
    ["@string.regex"] = { fg = colors.green },
    ["@comment"] = { fg = colors.green, italic = true },
    ["@keyword"] = { fg = colors.yellow },
    ["@function"] = { fg = colors.blue },
    ["@function.builtin"] = { fg = colors.blue },
    ["@variable"] = { fg = colors.fg },
    ["@variable.builtin"] = { fg = colors.fg },
    ["@constant"] = { fg = colors.yellow },
    ["@constant.builtin"] = { fg = colors.yellow },
    ["@type"] = { fg = colors.fg },
    ["@type.builtin"] = { fg = colors.fg },
    ["@parameter"] = { fg = colors.fg },
    ["@field"] = { fg = colors.fg },
    ["@property"] = { fg = colors.fg },
    ["@constructor"] = { fg = colors.blue },
    ["@punctuation.delimiter"] = { fg = colors.fg },
    ["@punctuation.bracket"] = { fg = colors.fg },
    ["@punctuation.special"] = { fg = colors.fg },
    ["@operator"] = { fg = colors.fg },
    ["@exception"] = { fg = colors.yellow },
    ["@namespace"] = { fg = colors.fg },
    ["@module"] = { fg = colors.fg },
    ["@decorator"] = { fg = colors.yellow },
    ["@tag"] = { fg = colors.fg },
    ["@tag.delimiter"] = { fg = colors.fg },
    ["@attribute"] = { fg = colors.yellow },
    ["@text"] = { fg = colors.fg },
    ["@text.strong"] = { fg = colors.fg, bold = true },
    ["@text.emphasis"] = { fg = colors.fg, italic = true },
    ["@text.underline"] = { fg = colors.fg, underline = true },
    ["@text.strike"] = { fg = colors.fg, strikethrough = true },
    ["@text.title"] = { fg = colors.blue, bold = true },
    ["@text.literal"] = { fg = colors.green },
    ["@text.uri"] = { fg = colors.blue, underline = true },
    ["@text.math"] = { fg = colors.blue },
    ["@text.environment"] = { fg = colors.yellow },
    ["@text.environment.name"] = { fg = colors.yellow },
    ["@text.reference"] = { fg = colors.blue },
    ["@text.note"] = { fg = colors.green },
    ["@text.warning"] = { fg = colors.yellow },
    ["@text.danger"] = { fg = colors.yellow },
    LspReferenceText = { bg = colors.blue },
    LspReferenceRead = { bg = colors.blue },
    LspReferenceWrite = { bg = colors.blue },
    LspCodeLens = { fg = colors.green },
    LspCodeLensSeparator = { fg = colors.green },
    LspSignatureActiveParameter = { fg = colors.yellow },
    DiagnosticError = { fg = colors.red },
    DiagnosticWarn = { fg = colors.yellow },
    DiagnosticInfo = { fg = colors.blue },
    DiagnosticHint = { fg = colors.green },
    DiagnosticOk = { fg = colors.green },
    DiagnosticVirtualTextError = { fg = colors.yellow },
    DiagnosticVirtualTextWarn = { fg = colors.yellow },
    DiagnosticVirtualTextInfo = { fg = colors.blue },
    DiagnosticVirtualTextHint = { fg = colors.green },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.green },
    Normal = { fg = colors.fg, bg = colors.bg },
    NormalFloat = { fg = colors.fg, bg = colors.bg },
    NormalNC = { fg = colors.fg, bg = colors.bg },
    Cursor = { fg = colors.bg, bg = colors.fg },
    CursorLine = { bg = colors.blue },
    CursorColumn = { bg = colors.blue },
    ColorColumn = { bg = colors.blue },
    SignColumn = { fg = colors.fg, bg = colors.bg },
    Folded = { fg = colors.green, bg = colors.blue },
    FoldColumn = { fg = colors.green, bg = colors.bg },
    LineNr = { fg = colors.yellow },
    CursorLineNr = { fg = colors.yellow, bold = true },
    CursorLineSign = { fg = colors.green },
    CursorLineFold = { fg = colors.green },
    DiffAdd = { fg = colors.green },
    DiffChange = { fg = colors.yellow },
    DiffDelete = { fg = colors.yellow },
    DiffText = { fg = colors.blue },
    IncSearch = { fg = colors.bg, bg = colors.yellow },
    Search = { fg = colors.bg, bg = colors.yellow },
    Substitute = { fg = colors.bg, bg = colors.yellow },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.selection },
    WarningMsg = { fg = colors.red },
    ErrorMsg = { fg = colors.red },
    ModeMsg = { fg = colors.fg },
    MoreMsg = { fg = colors.green },
    Question = { fg = colors.blue },
    QuickFixLine = { fg = colors.bg, bg = colors.yellow },
    StatusLine = { fg = colors.statusline_fg, bg = colors.statusline_bg },
    StatusLineNC = { fg = colors.statusline_fg, bg = colors.statusline_bg },
    TabLine = { fg = colors.green, bg = colors.blue },
    TabLineFill = { bg = colors.blue },
    TabLineSel = { fg = colors.fg, bg = colors.bg },
    VertSplit = { fg = colors.green },
    WinSeparator = { fg = colors.green },
    WildMenu = { fg = colors.bg, bg = colors.red },
    NonText = { fg = colors.fg },
    SpecialKey = { fg = colors.green },
    Whitespace = { fg = colors.green },
    EndOfBuffer = { fg = colors.bg },
    Conceal = { fg = colors.green },
    SpellBad = { undercurl = true, sp = colors.yellow },
    SpellCap = { undercurl = true, sp = colors.yellow },
    SpellLocal = { undercurl = true, sp = colors.blue },
    SpellRare = { undercurl = true, sp = colors.blue },
    Pmenu = { fg = colors.fg, bg = colors.blue },
    PmenuSel = { fg = colors.bg, bg = colors.blue },
    PmenuSbar = { bg = colors.blue },
    PmenuThumb = { bg = colors.green },
    PmenuKind = { fg = colors.blue },
    PmenuKindSel = { fg = colors.blue },
    PmenuExtra = { fg = colors.green },
    PmenuExtraSel = { fg = colors.green },
    PmenuMenu = { fg = colors.green },
    PmenuMenuSel = { fg = colors.green },
  }
end

return M
